source 'https://rubygems.org'

gem 'jekyll', '~> 2.5.3'
gem 'jekyll-redirect-from', '~> 0.9.0'
gem 'redcarpet', '~> 3.1'
gem 'albino', '~> 1.3'
gem 'kramdown', '~> 1.6.0'
gem 'jekyll-compass', '~> 1.1.0'
gem 'compass', '~> 0.12.7'
gem 'sass', '~> 3.2.19'
